import {
  BiCheckSquare,
  BiListOl,
  BiMovie,
  BiNews,
  BiStar,
  BiTrophy,
  BiTv,
} from "react-icons/bi"
import {
  FaAndroid,
  FaApple,
  FaAppleAlt,
  FaCoffee,
  FaEnvelope,
  FaFacebook,
  FaInstagram,
  FaLinkedinIn,
  FaLinux,
  FaPinterestP,
  FaPlaystation,
  FaRedditAlien,
  FaTelegramPlane,
  FaWhatsapp,
  FaWindows,
  FaXbox,
  FaYoutube,
} from "react-icons/fa"
import { FcGoogle } from "react-icons/fc"
import { ImBook } from "react-icons/im"
import { IoGameController } from "react-icons/io5"
import {
  LuChevronDown,
  LuCircle,
  LuLoader2,
  LuTrash,
  LuTwitter,
} from "react-icons/lu"
import {
  MdAccessTime,
  MdAccountCircle,
  MdAddShoppingCart,
  MdAnalytics,
  MdCategory,
  MdChevronLeft,
  MdChevronRight,
  MdClose,
  MdCode,
  MdContentCopy,
  MdCurrencyExchange,
  MdDarkMode,
  MdDashboard,
  MdDeveloperBoard,
  MdDiamond,
  MdDiscount,
  MdDownload,
  MdFolder,
  MdFormatBold,
  MdFormatItalic,
  MdFormatListBulleted,
  MdFormatListNumbered,
  MdFormatQuote,
  MdFormatStrikethrough,
  MdFormatUnderlined,
  MdHelpOutline,
  MdHorizontalRule,
  MdImage,
  MdLightMode,
  MdLocationOn,
  MdLogin,
  MdLogout,
  MdOutlineAdd,
  MdOutlineAdsClick,
  MdOutlineArrowBack,
  MdOutlineArrowForward,
  MdOutlineArticle,
  MdOutlineBalance,
  MdOutlineBrokenImage,
  MdOutlineCheck,
  MdOutlineComment,
  MdOutlineCreditCard,
  MdOutlineDelete,
  MdOutlineEdit,
  MdOutlineEditNote,
  MdOutlineFileUpload,
  MdOutlineHome,
  MdOutlineKeyboardArrowDown,
  MdOutlineLink,
  MdOutlineMenu,
  MdOutlineMoreVert,
  MdOutlinePermMedia,
  MdOutlineSave,
  MdOutlineSearch,
  MdOutlineSettings,
  MdOutlineTopic,
  MdOutlineViewSidebar,
  MdOutlineVisibility,
  MdOutlineVisibilityOff,
  MdPerson,
  MdStore,
  MdSupervisedUserCircle,
  MdUpdate,
  MdVpnKey,
} from "react-icons/md"
import { SiNintendoswitch } from "react-icons/si"

import { IndonesiaFlag, USAFlag } from "./flag"

export const Icon = {
  AccessTime: MdAccessTime,
  Account: MdAccountCircle,
  Add: MdOutlineAdd,
  Ads: MdOutlineAdsClick,
  Analytics: MdAnalytics,
  Android: FaAndroid,
  Apple: FaApple,
  AppleAlt: FaAppleAlt,
  ArrowBack: MdOutlineArrowBack,
  ArrowForward: MdOutlineArrowForward,
  Article: MdOutlineArticle,
  Balance: MdOutlineBalance,
  Book: ImBook,
  BrokenImage: MdOutlineBrokenImage,
  Category: MdCategory,
  Check: MdOutlineCheck,
  CheckSquare: BiCheckSquare,
  ChevronLeft: MdChevronLeft,
  ChevronRight: MdChevronRight,
  ChevronDown: LuChevronDown,
  Circle: LuCircle,
  Close: MdClose,
  Code: MdCode,
  Coffe: FaCoffee,
  Comment: MdOutlineComment,
  Copy: MdContentCopy,
  CreditCard: MdOutlineCreditCard,
  Currency: MdCurrencyExchange,
  Dark: MdDarkMode,
  Dashboard: MdDashboard,
  Developer: MdDeveloperBoard,
  Diamond: MdDiamond,
  Discount: MdDiscount,
  Download: MdDownload,
  Delete: MdOutlineDelete,
  EditNote: MdOutlineEditNote,
  Edit: MdOutlineEdit,
  Email: FaEnvelope,
  USAFlag: USAFlag,
  Facebook: FaFacebook,
  Folder: MdFolder,
  FormatBold: MdFormatBold,
  FormatItalic: MdFormatItalic,
  FormatListBulleted: MdFormatListBulleted,
  FormatListNumbered: MdFormatListNumbered,
  FormatQuote: MdFormatQuote,
  FormatStrikethrough: MdFormatStrikethrough,
  FormatUnderlined: MdFormatUnderlined,
  Game: IoGameController,
  GoogleColored: FcGoogle,
  Help: MdHelpOutline,
  Home: MdOutlineHome,
  HorizontalRule: MdHorizontalRule,
  Image: MdImage,
  IndonesiaFlag: IndonesiaFlag,
  Instagram: FaInstagram,
  KeyboardArrowDown: MdOutlineKeyboardArrowDown,
  Light: MdLightMode,
  Link: MdOutlineLink,
  Linkedin: FaLinkedinIn,
  Linux: FaLinux,
  ListOl: BiListOl,
  Location: MdLocationOn,
  Login: MdLogin,
  Logout: MdLogout,
  Media: MdOutlinePermMedia,
  Menu: MdOutlineMenu,
  MoreVert: MdOutlineMoreVert,
  Moon: MdDarkMode,
  Movie: BiMovie,
  News: BiNews,
  NintendoSwitch: SiNintendoswitch,
  Person: MdPerson,
  Pinterest: FaPinterestP,
  PlayStation: FaPlaystation,
  Reddit: FaRedditAlien,
  Save: MdOutlineSave,
  Settings: MdOutlineSettings,
  Search: MdOutlineSearch,
  Shop: MdStore,
  ShoppingCart: MdAddShoppingCart,
  SignIn: MdLogin,
  SignOut: MdLogout,
  Spinner: LuLoader2,
  Star: BiStar,
  Sun: MdLightMode,
  Telegram: FaTelegramPlane,
  Topic: MdOutlineTopic,
  Trash: LuTrash,
  Trophy: BiTrophy,
  TV: BiTv,
  Twitter: LuTwitter,
  Update: MdUpdate,
  UploadFile: MdOutlineFileUpload,
  Users: MdSupervisedUserCircle,
  ViewSidebar: MdOutlineViewSidebar,
  Visibility: MdOutlineVisibility,
  VisibilityOff: MdOutlineVisibilityOff,
  VpnKey: MdVpnKey,
  Xbox: FaXbox,
  WhatsApp: FaWhatsapp,
  Windows: FaWindows,
  Youtube: FaYoutube,
}
